/**
 * Named aliases over the generated schema.
 *
 * `src/types/database.ts` is regenerated by `npm run db:types` and anything
 * written into it is destroyed. These live here so regeneration is safe, and so
 * the app refers to `CommitmentRow` rather than
 * `Database['public']['Tables']['commitments']['Row']` at every call site.
 *
 * Because they're derived rather than declared, a column added or dropped in a
 * migration turns into a type error here the moment types are regenerated —
 * which is exactly what should happen.
 */
import type { Database, Tables, TablesInsert, TablesUpdate } from '@/types/database'

export type { Database, Json, Tables, TablesInsert, TablesUpdate } from '@/types/database'

// --- Rows -------------------------------------------------------------------

export type ProfileRow = Tables<'profiles'>
export type ProjectRow = Tables<'projects'>
export type PersonRow = Tables<'people'>
export type EventRow = Tables<'events'>
export type EventAttendeeRow = Tables<'event_attendees'>
export type NoteRow = Tables<'notes'>
export type NoteVersionRow = Tables<'note_versions'>
export type CommitmentRow = Tables<'commitments'>
export type DecisionRow = Tables<'decisions'>
export type DocumentRow = Tables<'documents'>
export type ChecklistTemplateRow = Tables<'checklist_templates'>
export type ChecklistItemRow = Tables<'checklist_items'>
export type MilestoneRow = Tables<'milestones'>
export type CommentRow = Tables<'comments'>
export type InboxItemRow = Tables<'inbox_items'>
export type DigestRow = Tables<'digests'>
export type AuditLogRow = Tables<'audit_log'>

export type CommitmentInsert = TablesInsert<'commitments'>
export type CommitmentUpdate = TablesUpdate<'commitments'>

// --- Enums ------------------------------------------------------------------

type Enums = Database['public']['Enums']

export type UserRole = Enums['user_role']
export type Sensitivity = Enums['sensitivity']
export type ProjectStatus = Enums['project_status']
export type Health = Enums['health']
export type Relationship = Enums['relationship']
export type EventType = Enums['event_type']
export type EventStatus = Enums['event_status']
export type AttendeeRole = Enums['attendee_role']
export type RsvpStatus = Enums['rsvp_status']
export type OwnerType = Enums['owner_type']
export type CommitmentStatus = Enums['commitment_status']
export type CommitmentSource = Enums['commitment_source']
export type MilestoneStatus = Enums['milestone_status']
export type CommentParent = Enums['comment_parent']
export type InboxSource = Enums['inbox_source']
